name: Delete Branch After PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    name: Deleting Branch ${{ github.event.pull_request.head.ref }}  
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Delete the merged branch
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Deleting branch: $BRANCH_NAME"
          git push origin --delete "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
