name: QC-AI Test
run-name: QC-AI Test || ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to Run"
        required: true
        default: "main"
      code_file:
        description: "What is your code file name? (without spaces, lowercase)"
        required: true
        default: "your_code"
      prompt_file:
        description: "What is your prompt file name? (without spaces, lowercase)"
        required: false
        default: ""
      checklist_file:
        description: "What is your checklist file name? (without spaces, lowercase)"
        required: false
        default: ""
  repository_dispatch:
    types:
      - trigger-qc-test

jobs:
  setup-aws-credentials:
    runs-on: ubuntu-24.04 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV

    - name: Install AWS CLI
      run: |
        # Install AWS CLI using Snap
        sudo snap install aws-cli --classic
        aws --version 

    - name: Install Python Dependencies
      run: |
        # Install Python dependencies
        python3 -m pip install --upgrade pip
        pip install boto3 python-dotenv

    - name: Run QC Script
      run: |
        ls -l .
        CODE_FILES="${{ github.event.inputs.code_file }}"
        PROMPT_FILE="${{ github.event.inputs.prompt_file }}"
        CHECKLIST_FILE="${{ github.event.inputs.checklist_file }}"
        OUTPUT_FILE="qc_output.log"

        # Convert comma-separated code files to space-separated and append .py
        CONTEXT_FILES=$(echo "$CODE_FILES" | tr ',' ' ' | sed 's/\([^ ]*\)/\1.py/g')

        if [[ -z "$PROMPT_FILE" && -z "$CHECKLIST_FILE" ]]; then
          echo "Running basic QC with context files: $CONTEXT_FILES"
          python qc.py --context $CONTEXT_FILES > "$OUTPUT_FILE" 2>&1
        else
          PROMPT_FILE="${PROMPT_FILE}.txt"
          CHECKLIST_FILE="${CHECKLIST_FILE}.txt"
          echo "Running QC with context: $CONTEXT_FILES, prompt: $PROMPT_FILE, checklist: $CHECKLIST_FILE"
          python qc.py --context $CONTEXT_FILES --prompt "$PROMPT_FILE" --checklist "$CHECKLIST_FILE" > "$OUTPUT_FILE" 2>&1
        fi
    - name: Display QC Output
      run: |
        echo "==== QC Script Output ===="
        cat qc_output.log

    - name: Create GitHub Issue on Error
      if: ${{ always() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Check for error status in QC output
        if grep -q '"status": "error"' qc_output.log; then
          echo "Error detected, parsing output and creating GitHub issues..."

          # Read and parse the JSON log
          ISSUE_TITLE="${{ github.workflow }} || ${{ github.event.inputs.branch }}"
          QC_OUTPUT=$(cat qc_output.log)

          # Parse the JSON for code and quality issues
          MARKDOWN_BODY=$(jq -r '
            [
              (
                "## Code Issues\n\n" +
                (.checks.code_issues[] | 
                  "**Line:** \( .line )  \n" +
                  "**Severity:** \( .severity )  \n" +
                  "**Message:** \( .message )  \n" +
                  "**Error Code:** ```\( .error_code )```  \n" +
                  "**Fix:** ```\( .fix )```  \n" +
                  "**Category:** \( .category )\n\n"
                )
              ) // "No Code Issues Found.\n\n",
              (
                "## Quality Issues\n\n" +
                (.checks.quality_issues[] | 
                  "**Issue:** \( .issue )  \n" +
                  "**Severity:** \( .severity )  \n" +
                  "**Impact:** \( .impact )  \n" +
                  "**Best Practice:** \( .best_practice )  \n" +
                  "**Fix:** ```\( .fix )```  \n\n"
                )
              ) // "No Quality Issues Found.\n\n"
            ] | join("\n")
          ' <<< "$QC_OUTPUT")

            # Create GitHub issue for each file
            gh issue create \
              --title "$ISSUE_TITLE" \
              --body "$MARKDOWN_BODY" \
              --repo "${{ github.repository }}"
          done
        else
          echo "No error detected, skipping issue creation."
        fi
